111223
George-ast/mynewrepo pull request #3
Opened 2023-12-11 15:23 UTC by George-ast

homework

2023-12-11 16:57 UTC, antohaUa requested changes
Required docstring with task description and single file for solution.
All other good

2023-12-11 16:57 UTC, antohaUa commented on home3.3.py
> +"""old_text."""
Please add task description into the docstring. Plus combine both files to have one file with full required solution

2023-12-13 18:05 UTC, George-ast commented on home3.3.py
> +"""old_text."""
done

2023-12-14 13:03 UTC, antohaUa approved these changes
Good

2023-12-14 13:03 UTC, antohaUa commented on home3.3.py
> +norway_text = 'Automatisering akselererer %syeblikket da roboter vil erobre planeten v%sr. (%s)' % ('ø', 'å', 'Æ')
These both lines should be out of docstring text.
This is code ( aka initial data)

2023-12-14 13:03 UTC, antohaUa commented on home3.3.py
> +    'vil erobre planeten v{1} ({2})').format(symbol1, symbol2, symbol3)
E128 continuation line under-indented for visual indent
Pay attention to indents too
```suggestion
t2 = ('Automatisering akselererer, {0}syeblikket da roboter'
      'vil erobre planeten v{1} ({2})').format(symbol1, symbol2, symbol3)
```

2023-12-14 16:52 UTC, merged