201223
George-ast/mynewrepo pull request #5
Opened 2023-12-20 20:40 UTC by George-ast

2023-12-20 22:44 UTC, antohaUa requested changes
Fixes required

2023-12-20 22:44 UTC, antohaUa commented on home5.1.py
> +if (people_records[6][2] > 30
./T_HOMETSAKS/Lesson_05/05_GeorgiyAstashenok.py:43:9: W503 line break before binary operator
./T_HOMETSAKS/Lesson_05/05_GeorgiyAstashenok.py:44:9: W503 line break before binary operator

2023-12-20 22:44 UTC, antohaUa commented on home5.1.py
> +people_records.append(new_record)
This operation will add record to the end. But you need to at at the beginning

2023-12-20 22:44 UTC, antohaUa commented on home5.1.py
> +people_records[5] = substitution
Python allows to do this in one line

2023-12-20 22:44 UTC, antohaUa commented on home5.1.py
> +if (people_records[6][2] > 30
Do not forget about hardcodes and `all()` ,` any()` constructions

2023-12-23 10:03 UTC, George-ast commented on home5.1.py
> +if (people_records[6][2] > 30
W503 line break before binary operator  у меня нет такой ошибки.  Прошелся еще раз flake8

2023-12-23 13:19 UTC, antohaUa approved these changes
Good

2023-12-23 13:19 UTC, antohaUa commented on home5.1.py
> +"""Modified list."""
for comments better to use lines started with '#'

2023-12-23 13:19 UTC, antohaUa commented on home5.1.py
> +result = all(people_records[i][2] >= 30 for i in indexes_check)
30 is hardcode - better to move it to the top as constant

2023-12-23 13:19 UTC, antohaUa commented on home5.1.py
> +indexes_check = [6, 10, 13]
These indexes also hardcodes - aka initial data - better to move to the top of the module as constant

2023-12-23 13:19 UTC, antohaUa commented on home5.1.py
> +    print(False)
NO sense cause result already has boolean value
just `print(result)`

2023-12-26 17:49 UTC, merged