070124
George-ast/mynewrepo pull request #8
Opened 2024-01-07 19:52 UTC by George-ast

2024-01-07 20:15 UTC, antohaUa requested changes
Algorithm should be improved

2024-01-07 20:15 UTC, antohaUa commented on home7.1.py
> +"""
Use simple comment lines smth aka 
`# checking something blah blah blah`

2024-01-07 20:15 UTC, antohaUa commented on home7.1.py
> +if (x < w) and (x < y) and (x < z):
Such set 
w, x, y, z = -1, -1, -1, 0  will brake your algorithm ))
Code should be updated

2024-01-08 16:55 UTC, George-ast commented on home7.1.py
> +if (x < w) and (x < y) and (x < z):
что значит обновить код ?)

2024-01-11 15:02 UTC, antohaUa approved these changes
Fixes required for other variables too

2024-01-27 10:17 UTC, merged